# camel case 
apiVersion: v1
# kind of object
kind: Pod
# use spaces not tabs
metadata:
  name: grafana
  #provide label on metadata block for service slectors
  labels:
    app: grafana-app 
#specifications 
spec:
# list in yaml 
  containers:
  - name: grafana-container
    image: grafana/grafana